version: '3'
services: 
  importer: 
    build: 
      context: ./data_importer 
      dockerfile: Dockerfile 
    depends_on: 
      - influxdb
    volumes:
      - ./data_importer:/home/ds/notebooks/app

    entrypoint: ["python",  "/home/ds/notebooks/app/import.py" ]
  influxdb: 
    image: influxdb:1.3.8-alpine
    volumes: 
      - ./:/var/lib/influxdb
    ports: 
      - "8086:8086"
    